export const BASES = ["U", "C", "A", "G"];

export const CODONS = {
  UUU: { nameKey: "phenylalanine", group: "hydrophobic" },
  UUC: { nameKey: "phenylalanine", group: "hydrophobic" },
  UUA: { nameKey: "leucine", group: "hydrophobic" },
  UUG: { nameKey: "leucine", group: "hydrophobic" },
  UCU: { nameKey: "serine", group: "polar" },
  UCC: { nameKey: "serine", group: "polar" },
  UCA: { nameKey: "serine", group: "polar" },
  UCG: { nameKey: "serine", group: "polar" },
  UAU: { nameKey: "tyrosine", group: "polar" },
  UAC: { nameKey: "tyrosine", group: "polar" },
  UAA: { nameKey: "stopSignal", group: "stop", special: "stop" },
  UAG: { nameKey: "stopSignal", group: "stop", special: "stop" },
  UGU: { nameKey: "cysteine", group: "cysteine" },
  UGC: { nameKey: "cysteine", group: "cysteine" },
  UGA: { nameKey: "stopSignal", group: "stop", special: "stop" },
  UGG: { nameKey: "tryptophan", group: "hydrophobic", single: true },

  CUU: { nameKey: "leucine", group: "hydrophobic" },
  CUC: { nameKey: "leucine", group: "hydrophobic" },
  CUA: { nameKey: "leucine", group: "hydrophobic" },
  CUG: { nameKey: "leucine", group: "hydrophobic" },
  CCU: { nameKey: "proline", group: "hydrophobic" },
  CCC: { nameKey: "proline", group: "hydrophobic" },
  CCA: { nameKey: "proline", group: "hydrophobic" },
  CCG: { nameKey: "proline", group: "hydrophobic" },
  CAU: { nameKey: "histidine", group: "polar" },
  CAC: { nameKey: "histidine", group: "polar" },
  CAA: { nameKey: "glutamine", group: "polar" },
  CAG: { nameKey: "glutamine", group: "polar" },
  CGU: { nameKey: "arginine", group: "positive" },
  CGC: { nameKey: "arginine", group: "positive" },
  CGA: { nameKey: "arginine", group: "positive" },
  CGG: { nameKey: "arginine", group: "positive" },

  AUU: { nameKey: "isoleucine", group: "hydrophobic" },
  AUC: { nameKey: "isoleucine", group: "hydrophobic" },
  AUA: { nameKey: "isoleucine", group: "hydrophobic" },
  AUG: {
    nameKey: "methionine",
    group: "hydrophobic",
    special: "start",
    single: true,
  },
  ACU: { nameKey: "threonine", group: "polar" },
  ACC: { nameKey: "threonine", group: "polar" },
  ACA: { nameKey: "threonine", group: "polar" },
  ACG: { nameKey: "threonine", group: "polar" },
  AAU: { nameKey: "asparagine", group: "polar" },
  AAC: { nameKey: "asparagine", group: "polar" },
  AAA: { nameKey: "lysine", group: "positive" },
  AAG: { nameKey: "lysine", group: "positive" },
  AGU: { nameKey: "serine", group: "polar" },
  AGC: { nameKey: "serine", group: "polar" },
  AGA: { nameKey: "arginine", group: "positive" },
  AGG: { nameKey: "arginine", group: "positive" },

  GUU: { nameKey: "valine", group: "hydrophobic" },
  GUC: { nameKey: "valine", group: "hydrophobic" },
  GUA: { nameKey: "valine", group: "hydrophobic" },
  GUG: { nameKey: "valine", group: "hydrophobic" },
  GCU: { nameKey: "alanine", group: "hydrophobic" },
  GCC: { nameKey: "alanine", group: "hydrophobic" },
  GCA: { nameKey: "alanine", group: "hydrophobic" },
  GCG: { nameKey: "alanine", group: "hydrophobic" },
  GAU: { nameKey: "asparticAcid", group: "negative" },
  GAC: { nameKey: "asparticAcid", group: "negative" },
  GAA: { nameKey: "glutamicAcid", group: "negative" },
  GAG: { nameKey: "glutamicAcid", group: "negative" },
  GGU: { nameKey: "glycine", group: "hydrophobic" },
  GGC: { nameKey: "glycine", group: "hydrophobic" },
  GGA: { nameKey: "glycine", group: "hydrophobic" },
  GGG: { nameKey: "glycine", group: "hydrophobic" },
};

export const LEGEND_GROUPS = [
  "hydrophobic",
  "start",
  "polar",
  "positive",
  "negative",
  "cysteine",
  "stop",
];
